CREATE TABLE customer (
  customer_id     NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  first_name      VARCHAR2(50) NOT NULL,
  last_name       VARCHAR2(50) NOT NULL,
  email           VARCHAR2(100) UNIQUE,
  phone           VARCHAR2(20),
  address         VARCHAR2(200),
  date_registered DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT pk_customer PRIMARY KEY (customer_id)
);
CREATE TABLE loan_officer (
  officer_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  first_name      VARCHAR2(50) NOT NULL,
  last_name       VARCHAR2(50) NOT NULL,
  branch          VARCHAR2(100),
  email           VARCHAR2(100) UNIQUE,
  CONSTRAINT pk_officer PRIMARY KEY (officer_id)
);
CREATE TABLE loan_application (
  application_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  customer_id     NUMBER NOT NULL,
  loan_amount     NUMBER(12,2) NOT NULL CHECK (loan_amount > 0),
  loan_type       VARCHAR2(50) NOT NULL,
  officer_id      NUMBER NOT NULL,
  application_date DATE DEFAULT SYSDATE NOT NULL,
  status          VARCHAR2(20) DEFAULT 'PENDING' NOT NULL CHECK (status IN ('PENDING','APPROVED','REJECTED','CANCELLED')),
  CONSTRAINT pk_application PRIMARY KEY (application_id),
  CONSTRAINT fk_app_customer FOREIGN KEY (customer_id) REFERENCES customer(customer_id),
  CONSTRAINT fk_app_officer FOREIGN KEY (officer_id) REFERENCES loan_officer(officer_id)
);
CREATE TABLE collateral (
  collateral_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  application_id  NUMBER NOT NULL,
  collateral_type VARCHAR2(50) NOT NULL,
  value           NUMBER(14,2) CHECK (value >= 0),
  description     VARCHAR2(4000),
  verified_date   DATE,
  CONSTRAINT pk_collateral PRIMARY KEY (collateral_id),
  CONSTRAINT fk_coll_application FOREIGN KEY (application_id) REFERENCES loan_application(application_id)
);
CREATE TABLE loan (
  loan_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  application_id  NUMBER UNIQUE NOT NULL, -- 1:1 with approved application
  approved_amount NUMBER(12,2) NOT NULL CHECK (approved_amount >= 0),
  interest_rate   NUMBER(5,2) NOT NULL CHECK (interest_rate >= 0),
  start_date      DATE,
  end_date        DATE,
  status          VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE','CLOSED','DEFAULTED')),
  CONSTRAINT pk_loan PRIMARY KEY (loan_id),
  CONSTRAINT fk_loan_application FOREIGN KEY (application_id) REFERENCES loan_application(application_id)
);
CREATE TABLE repayment (
  repayment_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  loan_id         NUMBER NOT NULL,
  amount_paid     NUMBER(12,2) NOT NULL CHECK (amount_paid >= 0),
  payment_date    DATE DEFAULT SYSDATE,
  remaining_balance NUMBER(14,2),
  CONSTRAINT pk_repayment PRIMARY KEY (repayment_id),
  CONSTRAINT fk_repayment_loan FOREIGN KEY (loan_id) REFERENCES loan(loan_id)
);
CREATE TABLE audit_log (
  log_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
  entity_name     VARCHAR2(100) NOT NULL,
  entity_id       NUMBER,
  action          VARCHAR2(20) NOT NULL,
  action_date     TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  user_id         NUMBER,
  details         VARCHAR2(4000),
  CONSTRAINT pk_audit PRIMARY KEY (log_id)
);
CREATE INDEX idx_customer_email ON customer(email);
CREATE INDEX idx_app_customer ON loan_application(customer_id);
CREATE INDEX idx_app_officer ON loan_application(officer_id);
CREATE INDEX idx_coll_app ON collateral(application_id);
CREATE INDEX idx_loan_app ON loan(application_id);
CREATE INDEX idx_repayment_loan ON repayment(loan_id);
CREATE INDEX idx_audit_user ON audit_log(user_id);

COMMIT;
