CREATE USER ODRY_ADMIN IDENTIFIED BY Odry;
GRANT CONNECT, RESOURCE TO ODRY_ADMIN;
GRANT PDB_DBA TO ODRY_ADMIN;
ALTER USER ODRY_ADMIN QUOTA UNLIMITED ON coll_data;
ALTER USER ODRY_ADMIN QUOTA UNLIMITED ON coll_index;
ALTER USER ODRY_ADMIN TEMPORARY TABLESPACE coll_temp;
