INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Ndahiro', 'eric.ndahiro1@example.com', '0788123456', 'Kigali - Gasabo - Kimironko');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alice', 'Uwase', 'alice.uwase1@example.com', '0789456123', 'Kigali - Kicukiro - Kagarama');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Habimana', 'jean.habimana2@example.com', '0722456789', 'Huye - Tumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Diane', 'Ishimwe', 'diane.ishimwe2@example.com', '0733567890', 'Musanze - Muhoza');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Patrick', 'Ngabo', 'patrick.ngabo1@example.com', '0798123477', 'Rubavu - Gisenyi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sarah', 'Mukamana', 'sarah.mukamana1@example.com', '0788654321', 'Nyarugenge - Nyamirambo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Kevin', 'Rutabana', 'kevin.rutabana1@example.com', '0789001122', 'Karongi - Bwishyura');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Rachel', 'Uwimpaye', 'rachel.uwimpaye1@example.com', '0722334455', 'Rwamagana - Kigabiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Samuel', 'Bikorimana', 'samuel.biko2@example.com', '0788765432', 'Nyagatare - Matimba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Yvette', 'Mukantabana', 'yvette.mukantabana1@example.com', '0733445566', 'Gicumbi - Byumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Daniel', 'Kwizera', 'daniel.kwizera1@example.com', '0789876543', 'Kayonza - Mukarange');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Florence', 'Uwimana', 'florence.uwimana2@example.com', '0788050505', 'Ruhango - Byimana');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Moise', 'Hategekimana', 'moise.hategekimana1@example.com', '0799001122', 'Gasabo - Kacyiru');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Clarisse', 'Umutoni', 'clarisse.umutoni1@example.com', '0787665544', 'Bugesera - Nyamata');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Louis', 'Gatera', 'louis.gatera1@example.com', '0789443322', 'Kamonyi - Runda');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aline', 'Mukasine', 'aline.mukasine1@example.com', '0722900112', 'Muhanga - Shyogwe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Henry', 'Munyaneza', 'henry.munyaneza1@example.com', '0788111222', 'Gakenke - Busengo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Naomi', 'Uwibutso', 'naomi.uwibutso2@example.com', '0787332211', 'Ngoma - Kibungo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eddy', 'Rutayisire', 'eddy.rutayisire2@example.com', '0789012345', 'Musanze - Cyuve');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Belinda', 'Mukazera', 'belinda.mukazera1@example.com', '0787998899', 'Kicukiro - Gahanga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Isaac', 'Twagirayezu', 'isaac.twagirayezu@example.com', '0786612345', 'Kigali - Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Ange', 'Mukarugwiza', 'ange.mukarugwiza@example.com', '0787321456', 'Huye - Ngoma');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Hagenimana', 'gilbert.hagenimana@example.com', '0787542311', 'Nyabihu - Jenda');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Vanessa', 'Uwineza', 'vanessa.uwineza@example.com', '0788876654', 'Rubavu - Rugerero');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jeanette', 'Mukamisha', 'jeanette.mukamisha@example.com', '0789543221', 'Kayonza - Rukara');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Herve', 'Nshimiyimana', 'herve.nshimiyimana@example.com', '0787456981', 'Rwamagana - Muyumbu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fiona', 'Niyonsaba', 'fiona.niyonsaba@example.com', '0723445567', 'Gasabo - Kibagabaga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Tom', 'Ndaruhutse', 'tom.ndaruhutse@example.com', '0786987123', 'Gicumbi - Cyumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Linda', 'Uwimbabazi', 'linda.uwimbabazi@example.com', '0787152399', 'Kicukiro - Kanombe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Bruce', 'Bizimana', 'bruce.bizimana@example.com', '0786432199', 'Huye - Mukoni');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Paula', 'Mukabera', 'paula.mukabera@example.com', '0738991234', 'Nyarugenge - Gitega');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Noel', 'Uwiragiye', 'noel.uwiragiye@example.com', '0789078567', 'Ngoma - Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Esther', 'Akingeneye', 'esther.aking@example.com', '0789054321', 'Nyagatare - Gatunda');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Junior', 'Nzeyimana', 'junior.nzeyimana@example.com', '0723344556', 'Bugesera - Mareba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Kelly', 'Uwumuremyi', 'kelly.uwumuremyi@example.com', '0786554112', 'Gatsibo - Kiziguro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Olivier', 'Nsengiyumva', 'olivier.nsengiyumva@example.com', '0789554323', 'Rusizi - Kamembe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Grace', 'Iradukunda', 'grace.iradukunda@example.com', '0789432111', 'Karongi - Murundi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aime', 'Murenzi', 'aime.murenzi@example.com', '0733221100', 'Kirehe - Nyamugari');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Theogene', 'Rwigema', 'theogene.rwigema@example.com', '0787443321', 'Kayonza - Ruramira');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Patricia', 'Niyitegeka', 'patricia.niyitegeka@example.com', '0787112234', 'Huye - Rusatira');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Lewis', 'Nizeyimana', 'lewis.nizeyimana@example.com', '0786234455', 'Nyanza - Busasamana');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandrine', 'Mukandayisenga', 'sandrine.mukandayisenga@example.com', '0787544432', 'Gasabo - Ndera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Kabanda', 'erickabanda@example.com', '0789654433', 'Kicukiro - Niboye');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Anna', 'Ingabire', 'anna.ingabire@example.com', '0787542210', 'Rulindo - Kinihira');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gerard', 'Mutabazi', 'gerard.mutabazi@example.com', '0799321100', 'Rubavu - Cyanzarwe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Bella', 'Uwitonze', 'bella.uwitonze@example.com', '0789411228', 'Gicumbi - Kageyo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sharon', 'Nkundwa', 'sharon.nkundwa@example.com', '0733556677', 'Kayonza - Kabarondo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Ian', 'Hirwa', 'ian.hirwa@example.com', '0789887765', 'Nyarugenge - Kigali City Market');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Mugisha', 'eric.mugisha@example.com', '0785123456', 'Kigali, Kicukiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alice', 'Uwera', 'alice.uwera@example.com', '0786234581', 'Kigali, Gasabo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Samuel', 'Ndayishimiye', 'samuel.ndayishimiye@example.com', '0789432156', 'Huye, Tumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Diane', 'Ingabire', 'diane.ingabire@example.com', '0787451290', 'Musanze, Cyuve');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Patrick', 'Hategekimana', 'patrick.hategekimana@example.com', '0789543217', 'Rubavu, Gisenyi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Yvette', 'Mukamana', 'yvette.mukamana@example.com', '0788893217', 'Kigali, Nyarugenge');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Niyonsenga', 'jean.niyonsenga@example.com', '0787213456', 'Rwamagana, Kigabiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Clarisse', 'Mutoni', 'clarisse.mutoni@example.com', '0785129834', 'Muhanga, Nyamabuye');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Kevin', 'Bizimana', 'kevin.bizimana@example.com', '0789912456', 'Kigali, Kimironko');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Christella', 'Uwase', 'christella.uwase@example.com', '0785641329', 'Nyagatare, Katabagemu');

INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Brian', 'Twagirayezu', 'brian.twagirayezu@example.com', '0787321945', 'Kicukiro, Kanombe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sylvie', 'Mukeshimana', 'sylvie.mukeshimana@example.com', '0786462913', 'Gicumbi, Byumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Thierry', 'Rwema', 'thierry.rwema@example.com', '0789874312', 'Kigali, Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aline', 'Umutoniwase', 'aline.umutoniwase@example.com', '0785342198', 'Rusizi, Kamembe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Habimana', 'claude.habimana@example.com', '0786921347', 'Karongi, Rubengera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fiona', 'Iradukunda', 'fiona.iradukunda@example.com', '0786427819', 'Bugesera, Nyamata');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Louis', 'Munyaneza', 'louis.munyaneza@example.com', '0789312784', 'Musanze, Busogo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Chantal', 'Nyirahabimana', 'chantal.nyirahabimana@example.com', '0785412983', 'Gatsibo, Kabarore');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Albert', 'Karangwa', 'albert.karangwa@example.com', '0784892137', 'Nyanza, Busasamana');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Joelle', 'Uwimbabazi', 'joelle.uwimbabazi@example.com', '0787421985', 'Kigali, Gikondo');

INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Hassan', 'Rutayisire', 'hassan.rutayisire@example.com', '0789234517', 'Rubavu, Rugerero');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Bella', 'Murekatete', 'bella.murekatete@example.com', '0783452198', 'Nyamasheke, Kibogora');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Olivier', 'Nkurunziza', 'olivier.nkurunziza@example.com', '0784519328', 'Kigali, Nyamirambo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Giselle', 'Umutoni', 'giselle.umutoni@example.com', '0786421987', 'Rulindo, Kinihira');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Isaac', 'Nshimiyimana', 'isaac.nshimiyimana@example.com', '0787123498', 'Kamonyi, Runda');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandrine', 'Uwamahoro', 'sandrine.uwamahoro@example.com', '0789982134', 'Rwamagana, Munyaga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Martin', 'Gashumba', 'martin.gashumba@example.com', '0786312498', 'Kayonza, Mukarange');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Florence', 'Mukabizimungu', 'florence.mukabizimungu@example.com', '0782134598', 'Musanze, Muhoza');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('David', 'Shema', 'david.shema@example.com', '0788412367', 'Kigali, Gisozi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Martha', 'Umunyana', 'martha.umunyana@example.com', '0786432197', 'Huye, Ngoma');

INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jeanette', 'Uwase', 'jeanette.uwase@example.com', '0787312456', 'Kicukiro, Sonatubes');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Emmanuel', 'Mutabazi', 'emmanuel.mutabazi@example.com', '0789543281', 'Karongi, Bwishyura');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Rosine', 'Mukantwari', 'rosine.mukantwari@example.com', '0785124978', 'Gicumbi, Rukomo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alain', 'Kagabo', 'alain.kagabo@example.com', '0782314956', 'Kigali, Kibagabaga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Josiane', 'Mukandoli', 'josiane.mukandoli@example.com', '0786974321', 'Rutsiro, Murunda');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Hagenimana', 'eric.hagenimana@example.com', '0786549123', 'Ruhango, Kinazi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Ange', 'Uwitonze', 'ange.uwitonze@example.com', '0789231876', 'Ngoma, Kibungo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Frank', 'Rukundo', 'frank.rukundo@example.com', '0787412983', 'Kigali, Masaka');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Yasmin', 'Umutesi', 'yasmin.umutesi@example.com', '0786423198', 'Rubavu, Nyundo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Denis', 'Murenzi', 'denis.murenzi@example.com', '0789812345', 'Kigali, Kimihurura');
