INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Ndahiro', 'eric.ndahiro1@example.com', '0788123456', 'Kigali - Gasabo - Kimironko');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alice', 'Uwase', 'alice.uwase1@example.com', '0789456123', 'Kigali - Kicukiro - Kagarama');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Habimana', 'jean.habimana2@example.com', '0722456789', 'Huye - Tumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Diane', 'Ishimwe', 'diane.ishimwe2@example.com', '0733567890', 'Musanze - Muhoza');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Patrick', 'Ngabo', 'patrick.ngabo1@example.com', '0798123477', 'Rubavu - Gisenyi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sarah', 'Mukamana', 'sarah.mukamana1@example.com', '0788654321', 'Nyarugenge - Nyamirambo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Kevin', 'Rutabana', 'kevin.rutabana1@example.com', '0789001122', 'Karongi - Bwishyura');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Rachel', 'Uwimpaye', 'rachel.uwimpaye1@example.com', '0722334455', 'Rwamagana - Kigabiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Samuel', 'Bikorimana', 'samuel.biko2@example.com', '0788765432', 'Nyagatare - Matimba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Yvette', 'Mukantabana', 'yvette.mukantabana1@example.com', '0733445566', 'Gicumbi - Byumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Daniel', 'Kwizera', 'daniel.kwizera1@example.com', '0789876543', 'Kayonza - Mukarange');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Florence', 'Uwimana', 'florence.uwimana2@example.com', '0788050505', 'Ruhango - Byimana');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Moise', 'Hategekimana', 'moise.hategekimana1@example.com', '0799001122', 'Gasabo - Kacyiru');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Clarisse', 'Umutoni', 'clarisse.umutoni1@example.com', '0787665544', 'Bugesera - Nyamata');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Louis', 'Gatera', 'louis.gatera1@example.com', '0789443322', 'Kamonyi - Runda');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aline', 'Mukasine', 'aline.mukasine1@example.com', '0722900112', 'Muhanga - Shyogwe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Henry', 'Munyaneza', 'henry.munyaneza1@example.com', '0788111222', 'Gakenke - Busengo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Naomi', 'Uwibutso', 'naomi.uwibutso2@example.com', '0787332211', 'Ngoma - Kibungo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eddy', 'Rutayisire', 'eddy.rutayisire2@example.com', '0789012345', 'Musanze - Cyuve');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Belinda', 'Mukazera', 'belinda.mukazera1@example.com', '0787998899', 'Kicukiro - Gahanga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Isaac', 'Twagirayezu', 'isaac.twagirayezu@example.com', '0786612345', 'Kigali - Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Ange', 'Mukarugwiza', 'ange.mukarugwiza@example.com', '0787321456', 'Huye - Ngoma');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Hagenimana', 'gilbert.hagenimana@example.com', '0787542311', 'Nyabihu - Jenda');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Vanessa', 'Uwineza', 'vanessa.uwineza@example.com', '0788876654', 'Rubavu - Rugerero');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jeanette', 'Mukamisha', 'jeanette.mukamisha@example.com', '0789543221', 'Kayonza - Rukara');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Herve', 'Nshimiyimana', 'herve.nshimiyimana@example.com', '0787456981', 'Rwamagana - Muyumbu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fiona', 'Niyonsaba', 'fiona.niyonsaba@example.com', '0723445567', 'Gasabo - Kibagabaga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Tom', 'Ndaruhutse', 'tom.ndaruhutse@example.com', '0786987123', 'Gicumbi - Cyumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Linda', 'Uwimbabazi', 'linda.uwimbabazi@example.com', '0787152399', 'Kicukiro - Kanombe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Bruce', 'Bizimana', 'bruce.bizimana@example.com', '0786432199', 'Huye - Mukoni');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Paula', 'Mukabera', 'paula.mukabera@example.com', '0738991234', 'Nyarugenge - Gitega');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Noel', 'Uwiragiye', 'noel.uwiragiye@example.com', '0789078567', 'Ngoma - Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Esther', 'Akingeneye', 'esther.aking@example.com', '0789054321', 'Nyagatare - Gatunda');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Junior', 'Nzeyimana', 'junior.nzeyimana@example.com', '0723344556', 'Bugesera - Mareba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Kelly', 'Uwumuremyi', 'kelly.uwumuremyi@example.com', '0786554112', 'Gatsibo - Kiziguro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Olivier', 'Nsengiyumva', 'olivier.nsengiyumva@example.com', '0789554323', 'Rusizi - Kamembe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Grace', 'Iradukunda', 'grace.iradukunda@example.com', '0789432111', 'Karongi - Murundi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aime', 'Murenzi', 'aime.murenzi@example.com', '0733221100', 'Kirehe - Nyamugari');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Theogene', 'Rwigema', 'theogene.rwigema@example.com', '0787443321', 'Kayonza - Ruramira');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Patricia', 'Niyitegeka', 'patricia.niyitegeka@example.com', '0787112234', 'Huye - Rusatira');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Lewis', 'Nizeyimana', 'lewis.nizeyimana@example.com', '0786234455', 'Nyanza - Busasamana');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandrine', 'Mukandayisenga', 'sandrine.mukandayisenga@example.com', '0787544432', 'Gasabo - Ndera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Kabanda', 'erickabanda@example.com', '0789654433', 'Kicukiro - Niboye');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Anna', 'Ingabire', 'anna.ingabire@example.com', '0787542210', 'Rulindo - Kinihira');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gerard', 'Mutabazi', 'gerard.mutabazi@example.com', '0799321100', 'Rubavu - Cyanzarwe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Bella', 'Uwitonze', 'bella.uwitonze@example.com', '0789411228', 'Gicumbi - Kageyo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sharon', 'Nkundwa', 'sharon.nkundwa@example.com', '0733556677', 'Kayonza - Kabarondo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Ian', 'Hirwa', 'ian.hirwa@example.com', '0789887765', 'Nyarugenge - Kigali City Market');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Mugisha', 'eric.mugisha@example.com', '0785123456', 'Kigali, Kicukiro');
-- Batch 1: Customer table inserts
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Munyakazi', 'claude.munyakazi1@example.com', '0787124589', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Godelive', 'Mutuyimana', 'godelive.mutuyimana2@example.com', '0789812347', 'Gacuriro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alexis', 'Ntirenganya', 'alexis.ntirenganya3@example.com', '0785532198', 'Tumba, Huye');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Divine', 'Uwintwari', 'divine.uwintwari4@example.com', '0787421675', 'Cyuve, Musanze');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Mukiza', 'jean.mukiza5@example.com', '0786923412', 'Gisenyi, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Ishimwe', 'liliane.ishimwe6@example.com', '0788432197', 'Nyarugenge, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alphonse', 'Habyarimana', 'alphonse.habyarimana7@example.com', '0789213458', 'Kigabiro, Rwamagana');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Ketia', 'Uwarukundo', 'ketia.uwarukundo8@example.com', '0785412369', 'Nyamabuye, Muhanga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Prosper', 'Biziyaremye', 'prosper.biziyaremye9@example.com', '0783219456', 'Kimironko, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mercy', 'Umuhoza', 'mercy.umuhoza10@example.com', '0789882123', 'Matimba, Nyagatare');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Nkuranga', 'gilbert.nkuranga11@example.com', '0786782145', 'Kanombe, Kicukiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Viviane', 'Mukamurenzi', 'viviane.mukamurenzi12@example.com', '0787632145', 'Byumba, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Innocent', 'Rwanyindo', 'innocent.rwanyindo13@example.com', '0785453219', 'Remera, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Hadidja', 'Uwase', 'hadidja.uwase14@example.com', '0787392114', 'Kamembe, Rusizi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aimable', 'Nkurikiyimana', 'aimable.nkurikiyimana15@example.com', '0786541293', 'Rubengera, Karongi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Olive', 'Iradukunda', 'olive.iradukunda16@example.com', '0784219357', 'Rilima, Bugesera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Paul', 'Mugabo', 'jeanpaul.mugabo17@example.com', '0788312496', 'Busogo, Musanze');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Mukabera', 'mireille.mukabera18@example.com', '0782134987', 'Kabarore, Gatsibo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Antoine', 'Mugenzi', 'antoine.mugenzi19@example.com', '0787429134', 'Busasamana, Nyanza');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Beatrice', 'Uwimbabazi', 'beatrice.uwimbabazi20@example.com', '0789642135', 'Gikondo, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Said', 'Nshimiyimana', 'said.nshimiyimana21@example.com', '0789134256', 'Rugerero, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Honorine', 'Murebwayire', 'honorine.murebwayire22@example.com', '0787641239', 'Gihombo, Nyamasheke');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Christophe', 'Gasana', 'christophe.gasana23@example.com', '0785521932', 'Nyamirambo, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Rosalie', 'Umulisa', 'rosalie.umulisa24@example.com', '0787912346', 'Shyorongi, Rulindo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Benoit', 'Rwabuhihi', 'benoit.rwabuhihi25@example.com', '0787213459', 'Runda, Kamonyi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Pacifique', 'Uwamwezi', 'pacifique.uwamwezi26@example.com', '0786892147', 'Munyaga, Rwamagana');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jeremie', 'Gakwaya', 'jeremie.gakwaya27@example.com', '0786541289', 'Mukarange, Kayonza');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Laurence', 'Kanyana', 'laurence.kanyana28@example.com', '0782119346', 'Muhoza, Musanze');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Bosco', 'Habiyaremye', 'jeanbosco.habiyaremye29@example.com', '0787942135', 'Gisozi, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jackie', 'Uwicyeza', 'jackie.uwicyeza30@example.com', '0785692143', 'Ngoma, Huye');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Philbert', 'Mukarugema', 'philbert.mukarugema31@example.com', '0787213946', 'Sonatubes, Kicukiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Regine', 'Mukandayisenga', 'regine.mukandayisenga32@example.com', '0785632147', 'Bwishyura, Karongi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Yannick', 'Rutagengwa', 'yannick.rutagengwa33@example.com', '0789821346', 'Rukomo, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Uwimana', 'claude.uwimana34@example.com', '0782513497', 'Kibagabaga, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Anitha', 'Mukantabana', 'anitha.mukantabana35@example.com', '0786123495', 'Murunda, Rutsiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Hagenimana', 'gilbert.hagenimana36@example.com', '0789231456', 'Kinazi, Ruhango');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Bruno', 'Mujyawamariya', 'bruno.mujyawamariya37@example.com', '0787153498', 'Kibungo, Ngoma');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Linda', 'Umurerwa', 'linda.umurerwa38@example.com', '0789612348', 'Masaka, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Shadia', 'Umwari', 'shadia.umwari39@example.com', '0788412391', 'Nyundo, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Muvunyi', 'fabrice.muvunyi40@example.com', '0787112934', 'Kimihurura, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alice', 'Uwera', 'alice.uwera41@example.com', '0787123456', 'Remera, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Emmanuel', 'Nkurunziza', 'emmanuel.nkurunziza42@example.com', '0786982143', 'Gatsibo, Kabarore');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Ange', 'Bizimana', 'ange.bizimana43@example.com', '0787456123', 'Nyarugenge, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Josiane', 'Mukandekezi', 'josiane.mukandekezi44@example.com', '0786543129', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fidel', 'Ndayambaje', 'fidel.ndayambaje45@example.com', '0787123498', 'Muhanga, Nyamabuye');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Claude', 'Ntakirutimana', 'jeanclaude.ntakirutimana46@example.com', '0786512349', 'Gicumbi, Byumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claire', 'Mukamana', 'claire.mukamana47@example.com', '0789213476', 'Rubavu, Gisenyi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eugene', 'Havyarimana', 'eugene.havyarimana48@example.com', '0787124983', 'Kayonza, Mukarange');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandra', 'Uwase', 'sandra.uwase49@example.com', '0786549872', 'Karongi, Rubengera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Nshimiyimana', 'eric.nshimiyimana50@example.com', '0787123984', 'Muhanga, Nyamabuye');
-- Batch 2: Customer table inserts
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Munyaneza', 'fabrice.munyaneza51@example.com', '0787451298', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alice', 'Mukamurenzi', 'alice.mukamurenzi52@example.com', '0786547123', 'Gisenyi, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Bizimungu', 'eric.bizimungu53@example.com', '0787123457', 'Muhanga, Nyamabuye');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Uwitonze', 'mireille.uwitonze54@example.com', '0789123456', 'Byumba, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Pierre', 'Munyandamutsa', 'jeanpierre.munyandamutsa55@example.com', '0787981234', 'Kigali, Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Munyabugingo', 'liliane.munyabugingo56@example.com', '0787124890', 'Kanombe, Kicukiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Nyiransabimana', 'claude.nyiransabimana57@example.com', '0786543127', 'Rwamagana, Munyaga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aimable', 'Mukarubibi', 'aimable.mukarubibi58@example.com', '0787456231', 'Kibungo, Ngoma');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Nshimiyimana', 'jean.nshimiyimana59@example.com', '0787213948', 'Shyorongi, Rulindo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandra', 'Uwera', 'sandra.uwera60@example.com', '0787123985', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Habimana', 'gilbert.habimana61@example.com', '0786543128', 'Gicumbi, Byumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Uwizeyimana', 'claude.uwizeyimana62@example.com', '0787456124', 'Kigali, Kimironko');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Innocent', 'Mutabaruka', 'innocent.mutabaruka63@example.com', '0787123499', 'Muhanga, Nyamabuye');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Munyampundu', 'liliane.munyampundu64@example.com', '0789213459', 'Nyarugenge, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alphonse', 'Uwitonze', 'alphonse.uwitonze65@example.com', '0786549873', 'Rubengera, Karongi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Claude', 'Nkurunziza', 'jeanclaude.nkurunziza66@example.com', '0787123986', 'Gisenyi, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Hirwa', 'mireille.hirwa67@example.com', '0787451236', 'Rukomo, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Uwase', 'eric.uwase68@example.com', '0787123987', 'Gikondo, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alice', 'Mukandayisenga', 'alice.mukandayisenga69@example.com', '0786543987', 'Masaka, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Nkurunziza', 'fabrice.nkurunziza70@example.com', '0787453987', 'Kimihurura, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Habineza', 'liliane.habineza71@example.com', '0787124980', 'Gisenyi, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Uwayezu', 'claude.uwayezu72@example.com', '0786543129', 'Nyamabuye, Muhanga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Mutangana', 'jean.mutangana73@example.com', '0787123491', 'Byumba, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aimable', 'Mukanyange', 'aimable.mukanyange74@example.com', '0787453981', 'Remera, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandra', 'Uwase', 'sandra.uwase75@example.com', '0787123982', 'Kimironko, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Niyonsaba', 'gilbert.niyonsaba76@example.com', '0786543122', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Munyandamutsa', 'claude.munyandamutsa77@example.com', '0787453983', 'Kigali, Gisozi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Innocent', 'Habyarimana', 'innocent.habyarimana78@example.com', '0787123492', 'Rulindo, Nyamasheke');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Paul', 'Uwayezu', 'jeanpaul.uwayezu79@example.com', '0786543123', 'Kibagabaga, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Mukashema', 'mireille.mukashema80@example.com', '0787453984', 'Busasamana, Nyanza');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Munyakazi', 'fabrice.munyakazi81@example.com', '0787123983', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alice', 'Habineza', 'alice.habineza82@example.com', '0786543124', 'Rwamagana, Munyaga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Uwarugaba', 'eric.uwarugaba83@example.com', '0787453985', 'Ngoma, Kibungo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Munyampundu', 'claude.munyampundu84@example.com', '0787123984', 'Kigali, Kimironko');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Uwayezu', 'liliane.uwayezu85@example.com', '0786543125', 'Nyundo, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Claude', 'Mukamurenzi', 'jeanclaude.mukamurenzi86@example.com', '0787453986', 'Masaka, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aimable', 'Nkurunziza', 'aimable.nkurunziza87@example.com', '0787123985', 'Gikondo, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandra', 'Mukandayisenga', 'sandra.mukandayisenga88@example.com', '0786543126', 'Kimihurura, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Habimana', 'gilbert.habimana89@example.com', '0787453987', 'Rukomo, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Niyonsaba', 'claude.niyonsaba90@example.com', '0787123986', 'Nyamabuye, Muhanga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Innocent', 'Munyakazi', 'innocent.munyakazi91@example.com', '0786543127', 'Kigali, Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Habineza', 'jean.habineza92@example.com', '0787453988', 'Gisenyi, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Uwera', 'mireille.uwera93@example.com', '0787123987', 'Byumba, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Mukamurenzi', 'fabrice.mukamurenzi94@example.com', '0786543128', 'Kimihurura, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Munyabugingo', 'liliane.munyabugingo95@example.com', '0787453989', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Habineza', 'claude.habineza96@example.com', '0787123988', 'Kigali, Gisozi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Paul', 'Uwamwezi', 'jeanpaul.uwamwezi97@example.com', '0786543129', 'Rulindo, Nyamasheke');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Nkurikiyimana', 'mireille.nkurikiyimana98@example.com', '0787453990', 'Rubengera, Karongi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Mukanyange', 'fabrice.mukanyange99@example.com', '0787123989', 'Gikondo, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alice', 'Uwitonze', 'alice.uwitonze100@example.com', '0786543130', 'Kimihurura, Kigali');
-- Batch 3: Customer table inserts
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Eric', 'Munyampundu', 'eric.munyampundu101@example.com', '0787453991', 'Kigali, Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Habimana', 'liliane.habimana102@example.com', '0786543131', 'Gisenyi, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Uwizeyimana', 'claude.uwizeyimana103@example.com', '0787123990', 'Nyundo, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Niyonsaba', 'jean.niyonsaba104@example.com', '0787453992', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aimable', 'Mukandamutsa', 'aimable.mukandamutsa105@example.com', '0786543132', 'Kigali, Kimironko');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandra', 'Uwera', 'sandra.uwera106@example.com', '0787123991', 'Masaka, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Nkurunziza', 'gilbert.nkurunziza107@example.com', '0787453993', 'Kibungo, Ngoma');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Mukamurenzi', 'claude.mukamurenzi108@example.com', '0786543133', 'Kigali, Gisozi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Innocent', 'Habiyaremye', 'innocent.habiyaremye109@example.com', '0787123992', 'Rubengera, Karongi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Paul', 'Mukanyange', 'jeanpaul.mukanyange110@example.com', '0787453994', 'Kimironko, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Uwayezu', 'mireille.uwayezu111@example.com', '0786543134', 'Rulindo, Nyamasheke');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Mukamurenzi', 'fabrice.mukamurenzi112@example.com', '0787123993', 'Byumba, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Habineza', 'liliane.habineza113@example.com', '0787453995', 'Kimihurura, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Nkurunziza', 'claude.nkurunziza114@example.com', '0786543135', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Mukandayisenga', 'jean.mukandayisenga115@example.com', '0787123994', 'Masaka, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aimable', 'Uwitonze', 'aimable.uwitonze116@example.com', '0787453996', 'Nyundo, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandra', 'Niyonzima', 'sandra.niyonzima117@example.com', '0786543136', 'Rwamagana, Munyaga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Munyampundu', 'gilbert.munyampundu118@example.com', '0787123995', 'Kigali, Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Uwimana', 'claude.uwimana119@example.com', '0787453997', 'Kimihurura, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Innocent', 'Habineza', 'innocent.habineza120@example.com', '0786543137', 'Byumba, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Paul', 'Nkurikiyimana', 'jeanpaul.nkurikiyimana121@example.com', '0787123996', 'Rulindo, Nyamasheke');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Mukamurenzi', 'mireille.mukamurenzi122@example.com', '0787453998', 'Gikondo, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Habimana', 'fabrice.habimana123@example.com', '0786543138', 'Rubengera, Karongi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Uwase', 'liliane.uwase124@example.com', '0787123997', 'Kimironko, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Munyandamutsa', 'claude.munyandamutsa125@example.com', '0787453999', 'Kigali, Kimironko');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Mukanyange', 'jean.mukanyange126@example.com', '0786543139', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aimable', 'Habimana', 'aimable.habimana127@example.com', '0787123998', 'Masaka, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandra', 'Uwitonze', 'sandra.uwitonze128@example.com', '0787454000', 'Gisenyi, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Mukanyange', 'gilbert.mukanyange129@example.com', '0786543140', 'Nyundo, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Niyonzima', 'claude.niyonzima130@example.com', '0787123999', 'Kigali, Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Innocent', 'Mukamurenzi', 'innocent.mukamurenzi131@example.com', '0787454001', 'Kimironko, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Paul', 'Habineza', 'jeanpaul.habineza132@example.com', '0786543141', 'Rulindo, Nyamasheke');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Uwitonze', 'mireille.uwitonze133@example.com', '0787124000', 'Byumba, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Mukanyange', 'fabrice.mukanyange134@example.com', '0787454002', 'Kigali, Kimironko');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Habineza', 'liliane.habineza135@example.com', '0786543142', 'Masaka, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Uwase', 'claude.uwase136@example.com', '0787124001', 'Rukomo, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Munyampundu', 'jean.munyampundu137@example.com', '0787454003', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aimable', 'Mukamurenzi', 'aimable.mukamurenzi138@example.com', '0786543143', 'Kigali, Gisozi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandra', 'Habimana', 'sandra.habimana139@example.com', '0787124002', 'Rwamagana, Munyaga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Uwitonze', 'gilbert.uwitonze140@example.com', '0787454004', 'Gikondo, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Mukanyange', 'claude.mukanyange141@example.com', '0786543144', 'Kimironko, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Innocent', 'Habimana', 'innocent.habimana142@example.com', '0787124003', 'Nyundo, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Paul', 'Mukanyange', 'jeanpaul.mukanyange143@example.com', '0787454005', 'Masaka, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Uwase', 'mireille.uwase144@example.com', '0786543145', 'Gisenyi, Rubavu');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Mukamurenzi', 'fabrice.mukamurenzi145@example.com', '0787124004', 'Kigali, Kimironko');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Habineza', 'liliane.habineza146@example.com', '0787454006', 'Kicukiro, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Uwitonze', 'claude.uwitonze147@example.com', '0786543146', 'Rulindo, Nyamasheke');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Mukanyange', 'jean.mukanyange148@example.com', '0787124005', 'Byumba, Gicumbi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aimable', 'Habimana', 'aimable.habimana149@example.com', '0787454007', 'Kimihurura, Kigali');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandra', 'Mukamurenzi', 'sandra.mukamurenzi150@example.com', '0786543147', 'Kigali, Gisozi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Munyakazi', 'claude.munyakazi@example.com', '0787124589', 'Kigali, Kicukiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Godelive', 'Mutuyimana', 'godelive.mutuyimana@example.com', '0789812347', 'Kigali, Gacuriro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alexis', 'Ntirenganya', 'alexis.ntirenganya@example.com', '0785532198', 'Huye, Tumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Divine', 'Uwintwari', 'divine.uwintwari@example.com', '0787421675', 'Musanze, Cyuve');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean', 'Mukiza', 'jean.mukiza@example.com', '0786923412', 'Rubavu, Gisenyi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Liliane', 'Ishimwe', 'liliane.ishimwe@example.com', '0788432197', 'Kigali, Nyarugenge');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alphonse', 'Habyarimana', 'alphonse.habyarimana@example.com', '0789213458', 'Rwamagana, Kigabiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Ketia', 'Uwarukundo', 'ketia.uwarukundo@example.com', '0785412369', 'Muhanga, Nyamabuye');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Prosper', 'Biziyaremye', 'prosper.biziyaremye@example.com', '0783219456', 'Kigali, Kimironko');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mercy', 'Umuhoza', 'mercy.umuhoza@example.com', '0789882123', 'Nyagatare, Matimba');

INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Nkuranga', 'gilbert.nkuranga@example.com', '0786782145', 'Kicukiro, Kanombe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Viviane', 'Mukamurenzi', 'viviane.mukamurenzi@example.com', '0787632145', 'Gicumbi, Byumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Innocent', 'Rwanyindo', 'innocent.rwanyindo@example.com', '0785453219', 'Kigali, Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Hadidja', 'Uwase', 'hadidja.uwase@example.com', '0787392114', 'Rusizi, Kamembe');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Aimable', 'Nkurikiyimana', 'aimable.nkurikiyimana@example.com', '0786541293', 'Karongi, Rubengera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Olive', 'Iradukunda', 'olive.iradukunda@example.com', '0784219357', 'Bugesera, Rilima');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Paul', 'Mugabo', 'jeanpaul.mugabo@example.com', '0788312496', 'Musanze, Busogo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Mireille', 'Mukabera', 'mireille.mukabera@example.com', '0782134987', 'Gatsibo, Kabarore');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Antoine', 'Mugenzi', 'antoine.mugenzi@example.com', '0787429134', 'Nyanza, Busasamana');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Beatrice', 'Uwimbabazi', 'beatrice.uwimbabazi@example.com', '0789642135', 'Kigali, Gikondo');

INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Said', 'Nshimiyimana', 'said.nshimiyimana@example.com', '0789134256', 'Rubavu, Rugerero');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Honorine', 'Murebwayire', 'honorine.murebwayire@example.com', '0787641239', 'Nyamasheke, Gihombo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Christophe', 'Gasana', 'christophe.gasana@example.com', '0785521932', 'Kigali, Nyamirambo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Rosalie', 'Umulisa', 'rosalie.umulisa@example.com', '0787912346', 'Rulindo, Shyorongi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Benoit', 'Rwabuhihi', 'benoit.rwabuhihi@example.com', '0787213459', 'Kamonyi, Runda');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Pacifique', 'Uwamwezi', 'pacifique.uwamwezi@example.com', '0786892147', 'Rwamagana, Munyaga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jeremie', 'Gakwaya', 'jeremie.gakwaya@example.com', '0786541289', 'Kayonza, Mukarange');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Laurence', 'Kanyana', 'laurence.kanyana@example.com', '0782119346', 'Musanze, Muhoza');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jean Bosco', 'Habiyaremye', 'jeanbosco.habiyaremye@example.com', '0787942135', 'Kigali, Gisozi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Jackie', 'Uwicyeza', 'jackie.uwicyeza@example.com', '0785692143', 'Huye, Ngoma');

INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Philbert', 'Mukarugema', 'philbert.mukarugema@example.com', '0787213946', 'Kicukiro, Sonatubes');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Regine', 'Mukandayisenga', 'regine.mukandayisenga@example.com', '0785632147', 'Karongi, Bwishyura');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Yannick', 'Rutagengwa', 'yannick.rutagengwa@example.com', '0789821346', 'Gicumbi, Rukomo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Claude', 'Uwimana', 'claude.uwimana@example.com', '0782513497', 'Kigali, Kibagabaga');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Anitha', 'Mukantabana', 'anitha.mukantabana@example.com', '0786123495', 'Rutsiro, Murunda');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Gilbert', 'Hagenimana', 'gilbert.hagenimana@example.com', '0789231456', 'Ruhango, Kinazi');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Bruno', 'Mujyawamariya', 'bruno.mujyawamariya@example.com', '0787153498', 'Ngoma, Kibungo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Linda', 'Umurerwa', 'linda.umurerwa@example.com', '0789612348', 'Kigali, Masaka');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Shadia', 'Umwari', 'shadia.umwari@example.com', '0788412391', 'Rubavu, Nyundo');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Fabrice', 'Muvunyi', 'fabrice.muvunyi@example.com', '0787112934', 'Kigali, Kimihurura');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Kevin', 'Mugisha', 'kevin.mugisha@example.com', '+250788123456', 'Kigali, Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Kevin', 'Mugisha', 'kevin.mugisha@example.com', '+250788123456', 'Kigali, Remera');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Sandrine', 'Mukandayisenga', 'sandrine.mukandayisenga@example.com', '+250782884422', 'Huye, Tumba');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Patrick', 'Habimana', 'patrick.habimana@example.com', '+250788991122', 'Kigali, Kicukiro');
INSERT INTO customer (first_name, last_name, email, phone, address) VALUES ('Alice', 'Uwimana', 'alice.uwimana@example.com', '+250784662210', 'Musanze, Muhoza');
