-- 50 rows of collateral linked to loan_application
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (1, 'Land', 2500000, 'Plot in Kigali, Nyarutarama', TO_DATE('2025-10-25','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (2, 'Vehicle', 1200000, 'Toyota Hilux 2019', TO_DATE('2025-10-28','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (3, 'House', 3000000, '2-bedroom house in Kicukiro', TO_DATE('2025-10-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (4, 'Land', 1800000, 'Small plot in Musanze', TO_DATE('2025-11-03','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (5, 'Equipment', 600000, 'Bakery machines', TO_DATE('2025-11-06','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (6, 'Vehicle', 1500000, 'Nissan Navara 2020', TO_DATE('2025-11-09','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (7, 'Land', 900000, 'Plot in Huye', TO_DATE('2025-11-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (8, 'House', 1400000, 'Single-family home in Kigali', TO_DATE('2025-11-15','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (9, 'Equipment', 750000, 'Printing press', TO_DATE('2025-11-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (10, 'Vehicle', 650000, 'Used Toyota Corolla', TO_DATE('2025-11-21','YYYY-MM-DD'));

-- Multiple collaterals for some applications
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (11, 'Land', 1200000, 'Plot in Nyagatare', TO_DATE('2025-11-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (11, 'Vehicle', 800000, 'Suzuki pickup', TO_DATE('2025-11-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (12, 'House', 3100000, 'Apartment in Kigali', TO_DATE('2025-11-27','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (13, 'Land', 600000, 'Small plot in Rwamagana', TO_DATE('2025-11-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (14, 'Vehicle', 1400000, 'Toyota Prado', TO_DATE('2025-12-03','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (15, 'Equipment', 1800000, 'Restaurant kitchen tools', TO_DATE('2025-12-06','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (16, 'Land', 950000, 'Plot in Kicukiro', TO_DATE('2025-12-09','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (17, 'House', 2200000, '3-bedroom house in Musanze', TO_DATE('2025-12-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (18, 'Vehicle', 800000, 'Used Mitsubishi L200', TO_DATE('2025-12-15','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (19, 'Equipment', 2200000, 'Printing machines', TO_DATE('2025-12-18','YYYY-MM-DD'));

INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (20, 'Land', 600000, 'Plot in Ruhango', TO_DATE('2025-12-21','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (21, 'House', 950000, 'Apartment in Kigali', TO_DATE('2025-12-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (22, 'Vehicle', 2200000, 'Toyota Land Cruiser', TO_DATE('2025-12-27','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (23, 'Equipment', 1400000, 'Construction machinery', TO_DATE('2025-12-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (24, 'Land', 800000, 'Plot in Kayonza', TO_DATE('2026-01-02','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (25, 'House', 3100000, 'Villa in Kigali', TO_DATE('2026-01-05','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (26, 'Vehicle', 1250000, 'Nissan Patrol', TO_DATE('2026-01-08','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (27, 'Equipment', 1800000, 'Café coffee machines', TO_DATE('2026-01-11','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (28, 'Land', 600000, 'Plot in Muhanga', TO_DATE('2026-01-14','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (29, 'House', 1400000, 'Small house in Kigali', TO_DATE('2026-01-17','YYYY-MM-DD'));

INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (30, 'Vehicle', 3100000, 'Mercedes Benz GLE', TO_DATE('2026-01-20','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (31, 'Land', 1250000, 'Plot in Musanze', TO_DATE('2026-01-23','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (32, 'House', 1800000, '3-bedroom house in Kigali', TO_DATE('2026-01-26','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (33, 'Vehicle', 600000, 'Used Honda CRV', TO_DATE('2026-01-29','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (34, 'Equipment', 1400000, 'Printing press', TO_DATE('2026-02-01','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (35, 'Land', 950000, 'Plot in Kicukiro', TO_DATE('2026-02-04','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (36, 'House', 2200000, 'Villa in Kigali', TO_DATE('2026-02-07','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (37, 'Vehicle', 800000, 'Used Toyota Hilux', TO_DATE('2026-02-10','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (38, 'Equipment', 1250000, 'Bakery machines', TO_DATE('2026-02-13','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (39, 'Land', 1800000, 'Plot in Nyabihu', TO_DATE('2026-02-16','YYYY-MM-DD'));

INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (40, 'House', 950000, 'Apartment in Kigali', TO_DATE('2026-02-19','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (41, 'Vehicle', 2200000, 'Toyota Land Cruiser', TO_DATE('2026-02-22','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (42, 'Equipment', 1400000, 'Construction machinery', TO_DATE('2026-02-25','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (43, 'Land', 800000, 'Plot in Kayonza', TO_DATE('2026-02-28','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (44, 'House', 3100000, 'Villa in Kigali', TO_DATE('2026-03-03','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (45, 'Vehicle', 1250000, 'Nissan Patrol', TO_DATE('2026-03-06','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (46, 'Equipment', 1800000, 'Café coffee machines', TO_DATE('2026-03-09','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (47, 'Land', 600000, 'Plot in Muhanga', TO_DATE('2026-03-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (48, 'House', 1400000, 'Small house in Kigali', TO_DATE('2026-03-15','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (49, 'Vehicle', 3100000, 'Mercedes Benz GLE', TO_DATE('2026-03-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (50, 'Equipment', 1250000, 'Bakery machines', TO_DATE('2026-03-21','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (1, 'Property', 12000000, 'Family house in Kigali', TO_DATE('2025-10-01','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (2, 'Vehicle', 4500000, 'Toyota Land Cruiser', TO_DATE('2025-10-05','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (3, 'Jewelry', 1500000, 'Gold rings and bracelets', TO_DATE('2025-10-10','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (4, 'Equipment', 7000000, 'Restaurant kitchen equipment', TO_DATE('2025-10-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (5, 'Savings', 2500000, 'Bank fixed deposit', TO_DATE('2025-10-15','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (6, 'Land', 10000000, 'Plot in Gasabo', TO_DATE('2025-10-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (7, 'Property', 8000000, 'Apartment in Nyarutarama', TO_DATE('2025-10-20','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (8, 'Vehicle', 6000000, 'Mercedes Benz', TO_DATE('2025-10-22','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (9, 'Jewelry', 1200000, 'Gold necklaces', TO_DATE('2025-10-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (10, 'Equipment', 5000000, 'Printing machines', TO_DATE('2025-10-26','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (11, 'Savings', 3000000, 'Bank savings account', TO_DATE('2025-10-28','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (12, 'Land', 9000000, 'Plot in Kicukiro', TO_DATE('2025-10-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (13, 'Property', 11000000, 'Duplex in Remera', TO_DATE('2025-11-02','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (14, 'Vehicle', 4000000, 'Honda CR-V', TO_DATE('2025-11-04','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (15, 'Jewelry', 1000000, 'Gold bracelets', TO_DATE('2025-11-06','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (16, 'Equipment', 6500000, 'Bakery ovens', TO_DATE('2025-11-08','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (17, 'Savings', 2000000, 'Bank fixed deposit', TO_DATE('2025-11-10','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (18, 'Land', 9500000, 'Plot in Nyarugenge', TO_DATE('2025-11-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (19, 'Property', 8500000, 'House in Kacyiru', TO_DATE('2025-11-14','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (20, 'Vehicle', 5500000, 'Toyota Hilux', TO_DATE('2025-11-16','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (21, 'Jewelry', 1300000, 'Gold chains', TO_DATE('2025-11-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (22, 'Equipment', 7200000, 'IT server equipment', TO_DATE('2025-11-20','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (23, 'Savings', 2800000, 'Bank savings account', TO_DATE('2025-11-22','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (24, 'Land', 9700000, 'Plot in Remera', TO_DATE('2025-11-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (25, 'Property', 12500000, 'Villa in Kacyiru', TO_DATE('2025-11-26','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (26, 'Vehicle', 4800000, 'Nissan Patrol', TO_DATE('2025-11-28','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (27, 'Jewelry', 1100000, 'Gold earrings', TO_DATE('2025-11-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (28, 'Equipment', 6700000, 'Construction machinery', TO_DATE('2025-12-02','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (29, 'Savings', 3500000, 'Bank term deposit', TO_DATE('2025-12-04','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (30, 'Land', 10200000, 'Plot in Kimihurura', TO_DATE('2025-12-06','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (31, 'Property', 9500000, 'Apartment in Kicukiro', TO_DATE('2025-12-08','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (32, 'Vehicle', 5300000, 'Ford Ranger', TO_DATE('2025-12-10','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (33, 'Jewelry', 1250000, 'Gold bangles', TO_DATE('2025-12-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (34, 'Equipment', 7100000, 'Medical equipment', TO_DATE('2025-12-14','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (35, 'Savings', 2400000, 'Bank savings account', TO_DATE('2025-12-16','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (36, 'Land', 9900000, 'Plot in Nyamirambo', TO_DATE('2025-12-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (37, 'Property', 11500000, 'House in Remera', TO_DATE('2025-12-20','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (38, 'Vehicle', 4600000, 'Toyota Prado', TO_DATE('2025-12-22','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (39, 'Jewelry', 1350000, 'Gold necklaces', TO_DATE('2025-12-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (40, 'Equipment', 6800000, 'Office furniture', TO_DATE('2025-12-26','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (1, 'Property', 12000000, 'Family house in Kigali', TO_DATE('2025-10-01','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (2, 'Vehicle', 4500000, 'Toyota Land Cruiser', TO_DATE('2025-10-05','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (3, 'Jewelry', 1500000, 'Gold rings and bracelets', TO_DATE('2025-10-10','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (4, 'Equipment', 7000000, 'Restaurant kitchen equipment', TO_DATE('2025-10-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (5, 'Savings', 2500000, 'Bank fixed deposit', TO_DATE('2025-10-15','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (6, 'Land', 10000000, 'Plot in Gasabo', TO_DATE('2025-10-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (7, 'Property', 8000000, 'Apartment in Nyarutarama', TO_DATE('2025-10-20','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (8, 'Vehicle', 6000000, 'Mercedes Benz', TO_DATE('2025-10-22','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (9, 'Jewelry', 1200000, 'Gold necklaces', TO_DATE('2025-10-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (10, 'Equipment', 5000000, 'Printing machines', TO_DATE('2025-10-26','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (11, 'Savings', 3000000, 'Bank savings account', TO_DATE('2025-10-28','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (12, 'Land', 9000000, 'Plot in Kicukiro', TO_DATE('2025-10-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (13, 'Property', 11000000, 'Duplex in Remera', TO_DATE('2025-11-02','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (14, 'Vehicle', 4000000, 'Honda CR-V', TO_DATE('2025-11-04','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (15, 'Jewelry', 1000000, 'Gold bracelets', TO_DATE('2025-11-06','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (16, 'Equipment', 6500000, 'Bakery ovens', TO_DATE('2025-11-08','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (17, 'Savings', 2000000, 'Bank fixed deposit', TO_DATE('2025-11-10','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (18, 'Land', 9500000, 'Plot in Nyarugenge', TO_DATE('2025-11-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (19, 'Property', 8500000, 'House in Kacyiru', TO_DATE('2025-11-14','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (20, 'Vehicle', 5500000, 'Toyota Hilux', TO_DATE('2025-11-16','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (21, 'Jewelry', 1300000, 'Gold chains', TO_DATE('2025-11-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (22, 'Equipment', 7200000, 'IT server equipment', TO_DATE('2025-11-20','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (23, 'Savings', 2800000, 'Bank savings account', TO_DATE('2025-11-22','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (24, 'Land', 9700000, 'Plot in Remera', TO_DATE('2025-11-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (25, 'Property', 12500000, 'Villa in Kacyiru', TO_DATE('2025-11-26','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (26, 'Vehicle', 4800000, 'Nissan Patrol', TO_DATE('2025-11-28','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (27, 'Jewelry', 1100000, 'Gold earrings', TO_DATE('2025-11-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (28, 'Equipment', 6700000, 'Construction machinery', TO_DATE('2025-12-02','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (29, 'Savings', 3500000, 'Bank term deposit', TO_DATE('2025-12-04','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (30, 'Land', 10200000, 'Plot in Kimihurura', TO_DATE('2025-12-06','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (31, 'Property', 9500000, 'Apartment in Kicukiro', TO_DATE('2025-12-08','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (32, 'Vehicle', 5300000, 'Ford Ranger', TO_DATE('2025-12-10','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (33, 'Jewelry', 1250000, 'Gold bangles', TO_DATE('2025-12-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (34, 'Equipment', 7100000, 'Medical equipment', TO_DATE('2025-12-14','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (35, 'Savings', 2400000, 'Bank savings account', TO_DATE('2025-12-16','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (36, 'Land', 9900000, 'Plot in Nyamirambo', TO_DATE('2025-12-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (37, 'Property', 11500000, 'House in Remera', TO_DATE('2025-12-20','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (38, 'Vehicle', 4600000, 'Toyota Prado', TO_DATE('2025-12-22','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (39, 'Jewelry', 1350000, 'Gold necklaces', TO_DATE('2025-12-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (40, 'Equipment', 6800000, 'Office furniture', TO_DATE('2025-12-26','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (41, 'Savings', 2600000, 'Bank savings account', TO_DATE('2025-12-28','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (42, 'Land', 10100000, 'Plot in Kiyovu', TO_DATE('2025-12-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (43, 'Property', 9700000, 'Apartment in Nyamirambo', TO_DATE('2026-01-02','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (44, 'Vehicle', 4900000, 'Mitsubishi Pajero', TO_DATE('2026-01-04','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (45, 'Jewelry', 1400000, 'Gold rings', TO_DATE('2026-01-06','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (46, 'Equipment', 7300000, 'Gym equipment', TO_DATE('2026-01-08','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (47, 'Savings', 2700000, 'Bank savings account', TO_DATE('2026-01-10','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (48, 'Land', 9800000, 'Plot in Gikondo', TO_DATE('2026-01-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (49, 'Property', 12300000, 'Villa in Kicukiro', TO_DATE('2026-01-14','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (50, 'Vehicle', 5200000, 'Toyota Land Cruiser', TO_DATE('2026-01-16','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (51, 'Jewelry', 1450000, 'Gold necklaces and bracelets', TO_DATE('2026-01-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (52, 'Equipment', 7500000, 'Factory machinery', TO_DATE('2026-01-20','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (53, 'Savings', 3000000, 'Bank term deposit', TO_DATE('2026-01-22','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (54, 'Land', 10500000, 'Plot in Gisozi', TO_DATE('2026-01-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (55, 'Property', 9800000, 'House in Kacyiru', TO_DATE('2026-01-26','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (56, 'Vehicle', 4700000, 'Toyota Corolla', TO_DATE('2026-01-28','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (57, 'Jewelry', 1250000, 'Gold rings', TO_DATE('2026-01-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (58, 'Equipment', 7200000, 'Restaurant equipment', TO_DATE('2026-02-01','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (59, 'Savings', 2600000, 'Bank savings account', TO_DATE('2026-02-03','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (60, 'Land', 9700000, 'Plot in Kimironko', TO_DATE('2026-02-05','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (61, 'Property', 11500000, 'Duplex in Nyarutarama', TO_DATE('2026-02-07','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (62, 'Vehicle', 4900000, 'Honda Civic', TO_DATE('2026-02-09','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (63, 'Jewelry', 1350000, 'Gold chains and earrings', TO_DATE('2026-02-11','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (64, 'Equipment', 6800000, 'Printing press', TO_DATE('2026-02-13','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (65, 'Savings', 2500000, 'Bank fixed deposit', TO_DATE('2026-02-15','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (66, 'Land', 10000000, 'Plot in Nyamirambo', TO_DATE('2026-02-17','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (67, 'Property', 12000000, 'House in Kimihurura', TO_DATE('2026-02-19','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (68, 'Vehicle', 5100000, 'Mitsubishi L200', TO_DATE('2026-02-21','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (69, 'Jewelry', 1400000, 'Gold necklaces', TO_DATE('2026-02-23','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (70, 'Equipment', 7000000, 'Medical lab equipment', TO_DATE('2026-02-25','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (71, 'Savings', 2800000, 'Bank savings account', TO_DATE('2026-02-27','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (72, 'Land', 10200000, 'Plot in Remera', TO_DATE('2026-02-29','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (73, 'Property', 10500000, 'Apartment in Kacyiru', TO_DATE('2026-03-02','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (74, 'Vehicle', 5300000, 'Toyota Rav4', TO_DATE('2026-03-04','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (75, 'Jewelry', 1300000, 'Gold rings and bangles', TO_DATE('2026-03-06','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (76, 'Equipment', 7200000, 'Bakery ovens and tools', TO_DATE('2026-03-08','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (77, 'Savings', 2600000, 'Bank term deposit', TO_DATE('2026-03-10','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (78, 'Land', 9800000, 'Plot in Gikondo', TO_DATE('2026-03-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (79, 'Property', 11800000, 'House in Kimihurura', TO_DATE('2026-03-14','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (80, 'Vehicle', 5000000, 'Toyota Prado', TO_DATE('2026-03-16','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (81, 'Jewelry', 1250000, 'Gold chains', TO_DATE('2026-03-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (82, 'Equipment', 6900000, 'IT servers', TO_DATE('2026-03-20','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (83, 'Savings', 2900000, 'Bank savings account', TO_DATE('2026-03-22','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (84, 'Land', 10100000, 'Plot in Kiyovu', TO_DATE('2026-03-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (85, 'Property', 12200000, 'Apartment in Nyarutarama', TO_DATE('2026-03-26','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (86, 'Vehicle', 4800000, 'Nissan Patrol', TO_DATE('2026-03-28','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (87, 'Jewelry', 1350000, 'Gold rings and earrings', TO_DATE('2026-03-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (88, 'Equipment', 7100000, 'Printing machines', TO_DATE('2026-04-01','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (89, 'Savings', 2500000, 'Bank fixed deposit', TO_DATE('2026-04-03','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (90, 'Land', 9900000, 'Plot in Nyamirambo', TO_DATE('2026-04-05','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (91, 'Property', 11700000, 'House in Remera', TO_DATE('2026-04-07','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (92, 'Vehicle', 5100000, 'Honda CR-V', TO_DATE('2026-04-09','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (93, 'Jewelry', 1400000, 'Gold necklaces', TO_DATE('2026-04-11','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (94, 'Equipment', 6700000, 'Medical equipment', TO_DATE('2026-04-13','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (95, 'Savings', 2800000, 'Bank term deposit', TO_DATE('2026-04-15','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (96, 'Land', 10300000, 'Plot in Kacyiru', TO_DATE('2026-04-17','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (97, 'Property', 11900000, 'Duplex in Kimihurura', TO_DATE('2026-04-19','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (98, 'Vehicle', 5200000, 'Toyota Hilux', TO_DATE('2026-04-21','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (99, 'Jewelry', 1300000, 'Gold bracelets', TO_DATE('2026-04-23','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (100, 'Equipment', 7400000, 'Office equipment', TO_DATE('2026-04-25','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (1, 'Property', 12000000, 'Family house in Kigali', TO_DATE('2025-10-01','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (2, 'Vehicle', 4500000, 'Toyota Land Cruiser', TO_DATE('2025-10-05','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (3, 'Jewelry', 1500000, 'Gold rings and bracelets', TO_DATE('2025-10-10','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (4, 'Equipment', 7000000, 'Restaurant kitchen equipment', TO_DATE('2025-10-12','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (5, 'Savings', 2500000, 'Bank fixed deposit', TO_DATE('2025-10-15','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (6, 'Land', 10000000, 'Plot in Gasabo', TO_DATE('2025-10-18','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (7, 'Property', 8000000, 'Apartment in Nyarutarama', TO_DATE('2025-10-20','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (8, 'Vehicle', 6000000, 'Mercedes Benz', TO_DATE('2025-10-22','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (9, 'Jewelry', 1200000, 'Gold necklaces', TO_DATE('2025-10-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (10, 'Equipment', 5000000, 'Printing machines', TO_DATE('2025-10-26','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (11, 'Land', 1200000, 'Plot in Nyagatare', TO_DATE('2025-11-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (11, 'Vehicle', 800000, 'Suzuki pickup', TO_DATE('2025-11-24','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (12, 'House', 3100000, 'Apartment in Kigali', TO_DATE('2025-11-27','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (13, 'Land', 600000, 'Small plot in Rwamagana', TO_DATE('2025-11-30','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (14, 'Vehicle', 1400000, 'Toyota Prado', TO_DATE('2025-12-03','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (15, 'Equipment', 1800000, 'Restaurant kitchen tools', TO_DATE('2025-12-06','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (16, 'Land', 950000, 'Plot in Kicukiro', TO_DATE('2025-12-09','YYYY-MM-DD'));
INSERT INTO collateral (application_id, collateral_type, value, description, verified_date) VALUES (17, 'House', 2200000, '3-bedroom house in Musanze', TO_DATE('2025-12-12','YYYY-MM-DD'));

