SELECT * FROM customer FETCH FIRST 20 ROWS ONLY;

SELECT * FROM loan_officer FETCH FIRST 20 ROWS ONLY;

SELECT * FROM loan_application FETCH FIRST 20 ROWS ONLY;

SELECT * FROM collateral FETCH FIRST 20 ROWS ONLY;

SELECT * FROM loan FETCH FIRST 20 ROWS ONLY;

SELECT * FROM repayment FETCH FIRST 20 ROWS ONLY;

SELECT * FROM audit_log FETCH FIRST 20 ROWS ONLY;
