CREATE PLUGGABLE DATABASE B_28450_Odry_loanCollateral_DB
ADMIN USER Odry_admin IDENTIFIED BY Odry
FILE_NAME_CONVERT = (
    'C:\ORACLEINSTALL\ORADATA\ORCL\PDBSEED\',
    'C:\ORACLEINSTALL\ORADATA\ORCL\B_28450_Odry_loanCollateral_DB\'
);
ALTER PLUGGABLE DATABASE B_28450_ODRY_LOANCOLLATERAL_DB OPEN READ WRITE;
ALTER SESSION SET CONTAINER = B_28450_ODRY_LOANCOLLATERAL_DB;

