CREATE TABLESPACE coll_data
DATAFILE 'C:\ORACLEINSTALL\ORADATA\ORCL\B_28450_ODRY_LOANCOLLATERAL_DB\coll_data01.dbf'
SIZE 100M AUTOEXTEND ON MAXSIZE UNLIMITED;

CREATE TABLESPACE coll_index
DATAFILE 'C:\ORACLEINSTALL\ORADATA\ORCL\B_28450_ODRY_LOANCOLLATERAL_DB\coll_index01.dbf'
SIZE 50M AUTOEXTEND ON MAXSIZE UNLIMITED; 

CREATE TEMPORARY TABLESPACE coll_temp
TEMPFILE 'C:\ORACLEINSTALL\ORADATA\ORCL\B_28450_ODRY_LOANCOLLATERAL_DB\coll_temp01.dbf'
SIZE 50M AUTOEXTEND ON MAXSIZE UNLIMITED;

// verify

SELECT tablespace_name, file_name FROM dba_data_files;


